I146 = "keukbYWKazcGYqwPfdeOkCwJgGjLZPGtYKAJLSjlybnKxCOrtCtrxpUKqKmIeaqHFnyENgfxRGOohkB"
tttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttt = "AEsNmcOAPcNShmfltAXJsTnlmjNZFuFhKWieydruUoxvuQAAcSZlsastgCWyiEJZsYsqlbphDCgshsC"
JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ = "pkPfHpdPFQUjrzKRTbZReOocLlvrpJlwRmLfSZtcvLCGuhIpSkCiPuRRSyMVQIPbZYCcOhrZFKstIxe"
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx = 290
gggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg = "UjyUJtDrHSCoVAslHKiEmlPeteuYUzdRlIPXbmuwYnJuEwmIQrVHBVsXSkiAOStpXiYkBpAqsdhsKei"
aAaAAaAAAaAaaAaaaAAAaAAAaAAAaaAaaaaAAaAaaaaaaAAAAaAaaaAaaaaaaaAAAAaAAaaAAAaaAAAAaAaaAaAaaAAaAaAAaaaaaAaAaAaAaaAAAaAaaAAAaaAAAAAaAAaaaaaa = "qtsyxjUDMqVyvLsDGsmIMGEXVDMzZYiEbTBOYgjZypOkAXskLIyOAuJyTAvLqgsFLEZqSMdQuYdlhmn"
VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV = "rjRDZaGoRtEQCeeqEVffiPpwppudsbPJxjNRQvaDBmwbsitMLdLCsPpxmuGLdgvLBzQeyDeqqKTiGAH"
aAaaaaaAAaaaAaAAaAaaAAaaaaaAaAaaAAaaaAAAaaAaAAaAaAAaAaaAaAaaAAAAAAaaaaaaAaAAaaAAaaAAAaaAAaaAAaaaAaAaaAaaAaaAaaAaAAAAAAaAAaaaaAaAAaaA = 296
u16546667690810125130 = "rEctwiyOulqjPQwkWlAdXpyXQhirKHibBrbSgYhklsNIrWVgfplcwBfIGYpcVyUwGOYMyvgNlQkenAd"
AAaaAAAAaAAAaaaaAAaAaaAaAaAAAAAAaaaAaAAAAAAaAAaAaAAaaAaaaAAAaaAaaaaAAaAaAAaAaaaAaAaAaAaAaaaAaaaaaAaAaaAaaaAAaAAAAaaAAAaAaAAaaAAA = 206
K16546667690768132126 = 328
t16546667690764265124 = 696
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff = "vOUnkQZaCKmNHnTznpBRSMkrHiNNhmUYhGvHtvfeOIAQoTXHnpImbtGVkZAROLbrgtOvXuWYJtKoHub"
k16546667690719512120 = 831
JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ = "kOmYBqUdwXCOmDycloYAEeXsBYmmsZnJWpFxEtkdlZRSLCbWjAEZnpzecJQECaoItwrLvkdaCHzxIWg"
tttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttt = "laIAcKNZWGsGcGuuXxFWnjaNfxUUIWRyGIlxaDrppySDszVdnXVGiXFfXzZVDiuSOEazMKxTwPPepbT"
uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu = 843
IIIllllllIlIIIIllIIIlIlllIIlIlllIIllllIlIIlIIIllIIIllllIllllIlIIlIIlIlIIIlIlIIIlllIIlIIIIIIlIIIIllIIIIIIIlIllIll = "vxVmfTBkumaRzKBXAubktXRqyKsyKoEXpgpOVEgRpjWGBpGvSXdubPvNoEwSZiQMeATtbuScpLojtaG"
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC = "dTbLwdqYTFkjuWLbAEIITEdUvEZAISftdZusfVJvAqOhouBHSPLOUhOnAbEGTXVEIkwGikSJkAdAtyC"
IllllIIIlIllIlllIlllllllIlIIlllIlIIlIllIlllIlIlllIlllIIlIllIIllllllIIllIllllllIllIllIIllIlIIlIIIlIIIlIlllIll = "LNKNjipORPHFIHzQMNRpBQeoKMNGtkOcGSquguhwtdxXURqhcVhkgOwkPoMhLwaQIYVvlBPKLZFjrJV"
R16546667690589747106 = "UlofwnfRCSlEiWfHweySVDBkxPdyIHJqmVOeTaxdrqPwEkgvROIwymVSESsZlKcMTPiiKOXKBJTQrxr"
aaAAaAAAaaAaaAAAAaAaAaaAAAAaAAaAaAaAAAaAAAaaaaaaaAaAAAaAaaaaAAAAAAAAaAaAaAAaAaaaAaAaaaAAaAAAaaAAaAAaaAAa = 320
K16546667690551887102 = 222
IIlIIlIllIIllIIllllIIllllIllIlIllIIIIlIllllIIlIIllIllIIIllIlIIIIIlllIllllllIIlIllllIIlIlIIllIllIIllI = "rcVnKGRKVOAUXqNccIhrfRZoFgRZludzMZHeJHmTqoZTUidFKnIuEUbPVwinVJvfwaKfuaiCxqWySHL"
AaaaAaAAaaaAAaaAaAAaaAAAAaAAaaAaAAAAAAAAaaAaaAAAaAaAaaaAAAaaAAaAaaaaAAaAaaAaaAAAaAAaaaAaaaaAAaAaAA = "nnLIXjPoGfSmkqPnOeyvcsyUVWbmgzcrvOsWDsOLdvoKFDMwwlMADvtZYpvVcvcnkLHvrCNOQKJWErA"
R96 = 391
p94 = 81
aaaAaaaAAAAaaaAaAaAaAAAaAAaAaAAAAAAaaaAaaAAaAAAaaAaAAaaAaaaAAAaAAAAAaaaAaAAaAAAAaaaAaaaAaaaA = "vIpAKxRPDKYxURzAwXyoJtAKCEulGadbjkWncvpwHoQKImRMjSPPsccLYTWMoTPrpecTgHgSruLvLgG"
lIIIlIlIllllllIlIlIIlIIIIIIIIllIIlIIlllllIIIIlIIlllIlIIIlIlIIlllIllIlllllllIIIIIlIIIIIlIIl = 300
s1654666769041101588 = "lEnVKQwjmWsvkIsyoTMJgLebNsuVufNpUKGXrFHZWRDqHtOBvvSNcTZnXpqhMwLquZfqaGXDkpHvTgZ"
V1654666769038461286 = "hfdsGwvAOnGMGcwScpSXmHqwoEPDJJRoUsERNffVYhaaOqvlwbKYEoqtYIpFLUQXajSIgstGRQgSWjO"
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD = "EEOMhajiyAxuooLDTUjkHcbFPmXyCetWfnfoEnRyzkBWenHTPplJarbVuyGrAdllZqOUEMMIutucbeZ"
i1654666769034925582 = 462
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc = "gAaCItJseVozyKJOVNPjumjzDyPmIiGwMVmdkENLYvOfqytNZnfvhqTISoOYalSqKwELKERoBzOIseS"
IllIIlIlllIIllIIIIlIIlIlllllIIIlIIlIIllllIIIllIIlIllIIIIIllllIlllIlllllIIIIIIl = "AiVPEcgJEkmeVoNWIOUIDRRQmRlXSgbBgWMHFrGDHWxWVsiWtpzXOtiNucqdtGCTZBjAAtCaiVmGfpU"
lIlIlIllIIlIIIIIIIIIIIIlIlIIIIlIIIIlIIIlllllIIIlllIlIIIlIIIlIlIlIIIlIIIIIIIl = "JrGGWCCMylvOVrFpKuQVVtbBYgizwmHwxdVcBBRTHxUjQSTvCRoHRKMGhdNueuDkMQKETJNtJtLyNYY"
aaAaAaaAaaaaaAAAAaAAAAAaaAAaaAaAAaaaAaaaAaAAAaaaAAaAaAAaaaAAaAaaaaAaaaaAaA = "NEjNBBhKVPjnFUtcOgJqKsxtVsMMaLgCqvyggqklcFTTlTSNsMhNLlAxTbfKPhzlQAboyqFajUEoXNo"
rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr = "hNrrCPlOaaTxPNZgaCWwQALeFpuzjdmeejotkfTzCPGybzDeZHBvhoiYBdLEHTswFrKcIQWvIxNcrfk"
q70 = 608
AaaaAaaaaAAaaAAAaAAAAaaAAaaaaAaaaaAaAaaAAaAAAAAAAAAaAaAAaAaAaaaAaaAa = 334
WZODQAnisYIeiPmHMRUrJJXPUYCPNdOvAxwtTXYBsMykzUnyTsayZVOQACbTgYzydFRJlydcIKSmAxn66 = "pcFSHOaKUweysTewadmDPtfJUFnrUoowJqBkLmZfRxMzIlvULWxMqqPFnQvSJYtIfWeXDfJxTuGlJBl"
t64 = 196
lIllIlllIIIlllIIIIIlIIlllIlllIIlIIlllIlIIIlIlllIIlllllIlllIlIl = "DpCBUyMLzgXeuyQYfyqEJSrIjDjPVErpklHlbcNLrPSgqDqEMFrBRFHRiltGyMbNQoHtCFupLzVBxNa"
IlIIlllllIIIlIlIIlIlIIIIlIIIlIIllllllIlIIIlllIllllIlIIIIllll = "zCsLxVsvsvtgEMLSnEQpIZZpqgrHIJohFKIBMAeXcbuhUjyEAirkrelEjaxRQqGdagOvEOGgYEBFFRC"
LnVLqQuJESTdDbZjUPzjkdQsfZGCYItyAETcIHKnFEStKqBggnQMlEbwBxNmmmjQJkMznIXXXYiLcLJ58 = "jVPegmBVTfjHRbjBCUpBJPvEPqSUGfhadQbkGYjszOfiYUeERKcEspbIeBHwLsrAZCgCxJylISqyXUh"
qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq = "pIBlJugfOXRtjJmXvKEdKufUCfvarJERKNBPqviIpxrvCSlTZtOALJHutIrVbRLHvHqgxCqWzCUsmDA"
AaAAAAaAAaaaaAaaAAAaAAaAAaAaaaaAaaAAAAaaaaAAaaaaaAAAAa = 327
UUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUU = 112
u1654666769008220750 = "zMCVTBYRcmMneetIIEUwtpvCsZCRqYWcLJYGrnIbCntugOUCpwIGdQtLROOLQWoRKHxGRAGgtVlojmr"
aAAaaAAaaaaaaaaaaaaAAaAAAAaAAaaAAAaAAaAaaaaAAaAa = 557
ooRwdufTmNdzPvxegnUBPklKBfVjebkVxEPTztUxwuvfWlaVnbPqkPpiOUSnJsBEagKFkAUqyTIcjqB46 = 370
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN = 165
d1654666769005442442 = "yNJLWyVxAYyXbrifDUJDfBMYfksNKTovdPNKqWiolOIymopIOjJPQzpWHvjpGhoJDsFHwMrkEbgjeCa"
G40 = "SyNKiGZWdudzseNXWPTdvAVTZjvTLVPzikhAzPtrxuPALDgLUbwyqeKNcTvcLWjwnNxSgKXovTZOKJe"
AaAAaAAAaaAaaAaaaAAaaaAaAAAAAaaAaAaaaA = 475
J36 = "FGOblOLXTCnRrOdXivCAoDqbBLyxmbNbCUXzwMlGPlPprrXdKCehKSmOaOoYjhvnfBkfVYgaEOcGyGw"
t34 = "yOwaJCtaXNfIlsJFlTSYLpWjKCEuBbMBxVxrwUMteXUaWiLqYbacoPBdQuxBXmtZYKyhxVymrrExfPT"
JtEmgEJMFzdyFrCvlUWAykLcPezuwNSTwhtJIxUrfmwgXdOYrGArCSjTvjPcLoszbiNBkuzWGCourBV32 = 763
f1654666769001076530 = "KudyObcDDRXFckYFPPzRheuqHxmhFEuwrNfZaEkuvIIrBqwDZaybZqdpobseDutzMgHeTdudfjIEiiV"
x28 = "uwetseojnUdtIMxQCxGKqNpAoEWdpSaoBoJSWvcuIMHYtAyCBqRTTvFXAQONvFbIMtaEDalhuLvENPM"
kyYsoWWPAwwEDRXOOsZqrYrsBrBCjsheuQyVNwavcmhnUmpoeerhMtQdNBysqIOYLoCTSYrxdliILbR26 = 579
AslQdIWoYxRRGTxXazPlUNsxWZPEhdrEFbyXgoXahkxyaqysjvRSJdrepruSuZznTiJFPkUONfXtgef24 = "rGZdXFozVQrvagifDeRgJSXjykeovPQfqNOdXVoTyfVmRhOBbFITaSvtNmYraZZjGMqMtqKemDZMhmI"
iiiiiiiiiiiiiiiiiiiiii = 651
jQfXDTmnymKaXeoHffBeLGfeFusmvHdBSnnGaRvywxJclRRLtODQYIZRORDWjMSFqDwCrgYyzblsmCo20 = "PdwzFGoBtNOmnVloPwocjMUtEkJQqLzcbZARoGrYAiqEqGjrdArpdogeQTiRuEcqawrkbNxEnxUHmPe"
lIIllllllIlIIIlIIl = "PefTRLGBZBznFQZLeDzzZSivFmByUsmwuQxGHQUwILTmCrtIKPuiknubCcldZaLmqOurjWavVlJPuBx"
AAAaAaAaAaAAaaaa = 337
rOEWjGiwcsPoykaOLQNhzNJVGgUZXOyFGEFIhrkryJtPvrbtcQCKBzrGGNoxfHySWoybwXvNoABIBQM14 = "jzbhNgAGwPahjxGqKIjAOxTTPZYzAWiljlwdXaktHlyqnvSRxVIGaPqTajqGMfBlAoyDTjgfESGHaLK"
F12 = "VLVvSWmPiyYdLQxFVwlbJrkMVsSppByWNyUkcBEoEVuUHnUqdFnmWEnJvyWsrVHCKIqePlVXwLaVBWL"
AAaAaaAaaa = 547
IlIIIIIl = 771
yOOFkzJafYHWXwJkYitXCmPeBiCLGlVsVshQAahVVXoVfZhorNZFZpaoBpbAvyRQGtyRayigrEVobZQ6 = "dOqerwQttITOzxlcHEvpDRuXbnNQdFScDtWTxPRgOrufXWuqhXXqMmzijqOKAMBzdmnRdUOMHkUGicn"
Illl = 680
GGfnLlIWAxnKUUKPmAwJMieAeJuRMzQGUgJtmrzQrcBZVhDrfwYoJGffbvRKflBhhBMQNjpBtFDkbgs2 = "SsoiMXtBwBwHnKuaWyVKdiKapLIVhtkRFmBRBJKMsXrMwwjraWvshdGPpMsruqjCCOgnrBOdCnAcwQa"

#pyobfuscate -i main.py -r True
import os,sys,time,random
from colorama import Fore,init,Back

O165466676894661551 = Fore.BLUE
IVUkpwmyZKExTqWRSExFXwJyBsFaBOqUMJZUsojXssnmYIMTqTevacpeOolLSjZrHcIeEFDlCttjhic2 = Fore.WHITE
IlI = Fore.RED
aAaa = Fore.GREEN
Z5 = Fore.BLACK
x6 = Fore.YELLOW

t7="\033[1;92m "
pppppppp="\033[1;97m"
AAAAAAAaa="\033[1;90m"
AAaaAAaaAA="\033[1;93m"
FFFFFFFFFFF="\033[1;95m"
aaaaAAaAaAAA="33[37;1m"
qduEIMECzoiZSlosZtQQrFNhsAbvMfezuPnxoJhCFdDgAGzSpkaeHrmzchXeLrVGBbGFnfiomYxkHCg13="\033[1;96m"
#Tulisan Background Merah
f165466676896656914="\033[1;0m\033[1;41mText\033[1;0m"

l1654666768967961515=random.choice([
"\033[1;92m",
"\033[1;97m",
"\033[1;90m",
"\033[1;93m",
"\033[1;95m",
"\033[1;96m"])

RRRRRRRRRRRRRRRR=random.choice([
"\033[1;93m",
"\033[1;96m",
"\033[1;95m",
"\033[1;92m",
"\033[1;90m",
"\033[1;97m"])

def printf(s):
    for fffffffffffffffff in s + "\n":
        sys.stdout.write(fffffffffffffffff)
        sys.stdout.flush()
        time.sleep(1./100)

def takok():
	fffffffffffffffff = input(f"{IVUkpwmyZKExTqWRSExFXwJyBsFaBOqUMJZUsojXssnmYIMTqTevacpeOolLSjZrHcIeEFDlCttjhic2}[{x6}?{IVUkpwmyZKExTqWRSExFXwJyBsFaBOqUMJZUsojXssnmYIMTqTevacpeOolLSjZrHcIeEFDlCttjhic2}] Mau Enc Lagi {aAaa}? {qduEIMECzoiZSlosZtQQrFNhsAbvMfezuPnxoJhCFdDgAGzSpkaeHrmzchXeLrVGBbGFnfiomYxkHCg13}({IVUkpwmyZKExTqWRSExFXwJyBsFaBOqUMJZUsojXssnmYIMTqTevacpeOolLSjZrHcIeEFDlCttjhic2}y/n{qduEIMECzoiZSlosZtQQrFNhsAbvMfezuPnxoJhCFdDgAGzSpkaeHrmzchXeLrVGBbGFnfiomYxkHCg13}){IVUkpwmyZKExTqWRSExFXwJyBsFaBOqUMJZUsojXssnmYIMTqTevacpeOolLSjZrHcIeEFDlCttjhic2}:")
	if fffffffffffffffff == "y" or fffffffffffffffff == "x6":
		main()
	if fffffffffffffffff == "n" or fffffffffffffffff == "N":
		sys.exit(f"{IVUkpwmyZKExTqWRSExFXwJyBsFaBOqUMJZUsojXssnmYIMTqTevacpeOolLSjZrHcIeEFDlCttjhic2}[{FFFFFFFFFFF}💫💫{IVUkpwmyZKExTqWRSExFXwJyBsFaBOqUMJZUsojXssnmYIMTqTevacpeOolLSjZrHcIeEFDlCttjhic2}] Thx For Using Tools{AAAAAAAaa}.....")
	if fffffffffffffffff == "" or fffffffffffffffff == " ":
		sys.exit(f"{IVUkpwmyZKExTqWRSExFXwJyBsFaBOqUMJZUsojXssnmYIMTqTevacpeOolLSjZrHcIeEFDlCttjhic2}[{IlI}•{IVUkpwmyZKExTqWRSExFXwJyBsFaBOqUMJZUsojXssnmYIMTqTevacpeOolLSjZrHcIeEFDlCttjhic2}] Masukkan Dengan Benar {IlI}!!")

def main():
	os.system("clear")
	printf (f"{l1654666768967961515}Subscribe Channel {IVUkpwmyZKExTqWRSExFXwJyBsFaBOqUMJZUsojXssnmYIMTqTevacpeOolLSjZrHcIeEFDlCttjhic2}Aing Dulu {l1654666768967961515}Sluur {aAaa}✓")
	os.system("xdg-open https://youtube.com/channel/UCyyIDnXYJlRI_-2pAQqKr0g")
	time.sleep(5)
	os.system("clear")
	printf (f"{RRRRRRRRRRRRRRRR}╔═╗{IVUkpwmyZKExTqWRSExFXwJyBsFaBOqUMJZUsojXssnmYIMTqTevacpeOolLSjZrHcIeEFDlCttjhic2}┌┐ ┌─┐┬ ┬┌─┐┌─┐┌─┐┌┬┐┌─┐   {l1654666768967961515}╔═╗{IVUkpwmyZKExTqWRSExFXwJyBsFaBOqUMJZUsojXssnmYIMTqTevacpeOolLSjZrHcIeEFDlCttjhic2}┬ ┬┌┬┐┬ ┬┌─┐┌┐┌")
	printf (f"{RRRRRRRRRRRRRRRR}║ ║{IVUkpwmyZKExTqWRSExFXwJyBsFaBOqUMJZUsojXssnmYIMTqTevacpeOolLSjZrHcIeEFDlCttjhic2}├┴┐├┤ │ │└─┐│  ├─┤ │ ├┤  {IlI}─ {l1654666768967961515}╠═╝{IVUkpwmyZKExTqWRSExFXwJyBsFaBOqUMJZUsojXssnmYIMTqTevacpeOolLSjZrHcIeEFDlCttjhic2}└┬┘ │ ├─┤│ ││││")
	printf (f"{RRRRRRRRRRRRRRRR}╚═╝{IVUkpwmyZKExTqWRSExFXwJyBsFaBOqUMJZUsojXssnmYIMTqTevacpeOolLSjZrHcIeEFDlCttjhic2}└─┘└  └─┘└─┘└─┘┴ ┴ ┴ └─┘   {l1654666768967961515}╩  {IVUkpwmyZKExTqWRSExFXwJyBsFaBOqUMJZUsojXssnmYIMTqTevacpeOolLSjZrHcIeEFDlCttjhic2} ┴  ┴ ┴ ┴└─┘┘└┘")
	print ("")
	aAAaAAAaAAAaAAAAaaaAaAaa = input(f"{IVUkpwmyZKExTqWRSExFXwJyBsFaBOqUMJZUsojXssnmYIMTqTevacpeOolLSjZrHcIeEFDlCttjhic2}[{x6}?{IVUkpwmyZKExTqWRSExFXwJyBsFaBOqUMJZUsojXssnmYIMTqTevacpeOolLSjZrHcIeEFDlCttjhic2}] Input Files {IlI}:{IVUkpwmyZKExTqWRSExFXwJyBsFaBOqUMJZUsojXssnmYIMTqTevacpeOolLSjZrHcIeEFDlCttjhic2} ")
	YYYYYYYYYYYYYYYYYYYYYYYYY = input(f"{IVUkpwmyZKExTqWRSExFXwJyBsFaBOqUMJZUsojXssnmYIMTqTevacpeOolLSjZrHcIeEFDlCttjhic2}[{x6}?{IVUkpwmyZKExTqWRSExFXwJyBsFaBOqUMJZUsojXssnmYIMTqTevacpeOolLSjZrHcIeEFDlCttjhic2}] Name Files {IlI}:{IVUkpwmyZKExTqWRSExFXwJyBsFaBOqUMJZUsojXssnmYIMTqTevacpeOolLSjZrHcIeEFDlCttjhic2} ")
	if aAAaAAAaAAAaAAAAaaaAaAaa == "" or aAAaAAAaAAAaAAAAaaaAaAaa == " ":
		sys.exit(f"{IVUkpwmyZKExTqWRSExFXwJyBsFaBOqUMJZUsojXssnmYIMTqTevacpeOolLSjZrHcIeEFDlCttjhic2}[{IlI}•{IVUkpwmyZKExTqWRSExFXwJyBsFaBOqUMJZUsojXssnmYIMTqTevacpeOolLSjZrHcIeEFDlCttjhic2}] Masukkan Dengan Benar {IlI}!!")
	if YYYYYYYYYYYYYYYYYYYYYYYYY == "" or YYYYYYYYYYYYYYYYYYYYYYYYY == " ":
		sys.exit(f"{IVUkpwmyZKExTqWRSExFXwJyBsFaBOqUMJZUsojXssnmYIMTqTevacpeOolLSjZrHcIeEFDlCttjhic2}[{IlI}•{IVUkpwmyZKExTqWRSExFXwJyBsFaBOqUMJZUsojXssnmYIMTqTevacpeOolLSjZrHcIeEFDlCttjhic2}] Masukkan Dengan Benar {IlI}!!")
	os.system(f"cat '{aAAaAAAaAAAaAAAAaaaAaAaa}' > {YYYYYYYYYYYYYYYYYYYYYYYYY}")
	os.system(f"pyobfuscate -i {YYYYYYYYYYYYYYYYYYYYYYYYY} -r True")
	print ("")
	print (f"{IVUkpwmyZKExTqWRSExFXwJyBsFaBOqUMJZUsojXssnmYIMTqTevacpeOolLSjZrHcIeEFDlCttjhic2}[{x6}---{IVUkpwmyZKExTqWRSExFXwJyBsFaBOqUMJZUsojXssnmYIMTqTevacpeOolLSjZrHcIeEFDlCttjhic2}] Encrypting Tools {IlI}!!!!")
	time.sleep(3)
	printf (f"{IVUkpwmyZKExTqWRSExFXwJyBsFaBOqUMJZUsojXssnmYIMTqTevacpeOolLSjZrHcIeEFDlCttjhic2}[{aAaa}✓{IVUkpwmyZKExTqWRSExFXwJyBsFaBOqUMJZUsojXssnmYIMTqTevacpeOolLSjZrHcIeEFDlCttjhic2}] Your File Saved{IlI}:{aAaa}{YYYYYYYYYYYYYYYYYYYYYYYYY}")
	takok()

if "__main__":
	main()

Z165466676898697611 = "DlrGrBIGxRxIVEOiijvUwuBoTAzcDvLmGKvMdQmQyXtXwpZvrXiioHYZuYGsOesEfEFYyeSJUCoDkxB"
aaA = "lMKulirkndwGdMPyUcgobliJXksTGlfwtvfaMSTjKkpaVQNpWmZXQVGsPrhEQVOAZJDxNysoPWgmHbK"
ALdtHrPjeAaBnjQdUvNpJuAdTPorsSKyibnswEzISOdcCGjRqtHuzVuHwbmkUNfGiCyZGOFwClqHipU5 = "enfdGpnQayMuFsKyTbRBjbbdFlhAnWkTMqlCKFoScZphhFhSMxvTROxCswZfTlVqwDZMnRqxpkiTTNu"
kkkkkkk = 228
nnnnnnnnn = 304
llIlllIlllI = "RflmFquphqKlnoQkRlPOheyCqgvyGrxwxtyPGFuPhOpAPRVZXfxglUpEBgjrbexbeyyrVDSKjFdBTcO"
AAAAAAAAAAAAA = "vDTsYZbaoYLZIjkfuefZFIQCbESxHjTZLPurSjwFEqbajaIzbNOIvCJYuRkMWUSDVsyvICHVXSwOuZS"
W15 = "ccYHsAJvesMqlAOtpXxIVRRHMYKdPnuOHvdneKXvsCVFLDbhrCUFLmMHvgXczCjzQCBSwuYTFwTnURF"
hpcgaAKYmjEvTljpFzyhEmcArFYvGroCvPYRBLKmUBPmJUhJwLrkilQopwSDFaPzSZgIWJKyTkzLnrk17 = "nMcGesltFHMhFDHDotqZDDoFbqusXEcTrrrsoucTQaCoRZtOlqkDazSokgSQIbouCFikTSjdOOzPkIv"
bbbbbbbbbbbbbbbbbbb = "aNtatcEvqEsWrJUeSRRquwGjzaMQrKVtpesSeJuvqMmOzzZLtauCLdhVlOjsgslZXlGDfuWOsCwVItL"
ukaBgrymqdEMBkgJJwzUvBJRUoPehMDtSrlPOftFwGBUAOALMVBGoityCisaCAKIcvUlYATIuPowDbO21 = 204
lllIIllIIlIIIlIIIIlIllI = "oYZgNexvZYkkXNgPiuzyWUyZdzxgbAwZuOVrJhStNTyCfywZdetpdjTkoNXIAulQMAJfMXxlryzLzxl"
aAAaaAAAAAAaAaaAAAaAAAaaa = "WBLoKQPentxzsPxFXOUtTcRGHuByesIcVVQJHTHnHgzkNRjXSYgukYuPGnyyaZrBylZnqlTdfmNOIuA"
q165466676899949327 = "vLEJjsXrpdppZnCeklxWcIEDXMQmElYoFnqbhNbQwJGbaRIdmrQekkpiCKDLqMcCVPKzKcxGkDbhxMy"
llIlIlIlllIlllIlIIIIllIIllIlI = "SbhUvZBCzIUJypgjmvpJhBMJwTgajqyjwxjbIodYHMMAOjzFGUVBqipJGuoRqAPhEMycCcvXptsQehY"
kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk = 623
m1654666769002002733 = "TMXGuEVJNdvLywBCdFHSaBqTcaKqHfZqhWkPoobrBxXZUjBnOFgeNzWwiPLBCIhAVIsWLoWwhPAewEq"
IIIlIlIIIIllIIllIllIIllIIIlIllIIllI = "iOEoYnnJbMMzUjTmSYHjwyjzhXwmLMDkAGSCYFTRHJERKcAcEBvEoIpDzZGUohsKWpFaoGLuixhYgEA"
wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww = 504
M39 = 596
IIIlIIllIlIIlIlIIIIIllIllIIllIIIIlIIIIIll = "eSowxrHHfJYJUwcidGrvTXtFjfRPPtzAPBfPgWJYJEBfLYZhzBLxUYNHfrklAVqYGQQSwrYOHSViOdG"
U1654666769005519643 = 646
JJzKYzTfMHxLWwTjPsbYEydzZUjdlqJeKNDwNgsbDBnnNANRDsTiuvtvcdCECzmvYIRgfsLbjJkiXYc45 = "qPpeHktNjugkdUXlJreuIZenQnCksEEMqZQUBGIjXQJMHgEGaBhnfUDNGyvwjGIsyZRpLbBGOPuyrmf"
IlIlIlIlIlllIlIllIIlIllllIlllIIIlIlIIIIlIlIIllI = 366
y49 = "GYumzikXxZuDuHueDaezRGvOFuAEfRkkSOYxnlUVxoHgOcXzSoqoGBGmUdvZkUtKnjlNRXeuNgXixir"
v51 = "giXRucHHFypfkhUDwbmELFfAGVcBtUFVbCtCcGMaMIklDSkDezgjbCNdhvvrjEEoqfpoIOdbrPKBRBe"
aaaAaaaaAaaAAaAAaAaaaAaAaaaaAAAaaAAaaaAaaAaaaaAaaAaAA = "sYmkFBIgovmfHIvoexwXuaEiyBvCgwhYDBQGXQJAAqZpHZiQdYRkCNMuqSJfbPkKUcZfQYFFCYJUcVH"
AAaAAAAAaaAaaAAAaAAAaAaAAAAaaaAAAaAaAaAaAAaAAaAaAaaAAaA = "yxravAnNiiKtCcFRVqxdtYXcnOJcGeNhqWLgcMnduVUbFACDTSKKRUhjsqGITfXyMztQiOxTFPXgBGZ"
c165466676901112357 = 553
IIlIlIIIlIlllIlIlIIIIllIIIIllIllIIlIIllllIIIlIIIlIllIlIlllI = 429
aAaAAaaAAAaaaAAAaaaAaaAaAAaaaAaaAaaAAAaAAaAAAaAaaAAAAaaaaaAaa = 431
aaAaaAaaaAAAaAaAaaaaAaAaAAaAAAaAAaAaAAAAAAAaaaAaAaAaaaAAaaaAaaa = "cgzdnXCttOWOQoqNesFWAKxaUDooLpkIyNkJaWZbzlbGVCbbPYXeTegbFMkgxTefosaqLkGtAuXCEAu"
pgJyXJnSumZhtpGpicNXzWoGDxpsicWQXHClOvScSIWAZfefKfvFGdkBkIwfyGCGXEPSGJKJDfmwdqO65 = "dVsjMYjdQoCHwADfrHYQIjUhtHOkuEQqGwmEOmFFHwcGHaQDbbRrxKaZamViAtwqDlikRwxzFUbTXGI"
IllllIIIlIlIllIIlIIllIllIIIlllllIlIllllIIlIlIlllIlIllIlllllIllllIII = "BngocZwCLoKVXHOLYQOpyophfzdWprwSmvQYDLlBDHnJBcLfshImukcZJNhkekeasCcEJhrVJqsisFc"
IllIlIlIIlIIllIIlIIllIIIllIllllIIIIllIlllIIIIIIlIIlllIlIIIIIlIIllIIIl = 177
aaaaAaaaAAAaAaAAAaAAAAAAAaAAaAAAAaaaAAaaAaAAaAaaaaaaAaaaAaAAaaaaaaaaaAa = "DOAycTuZYtuqaWFqePcGCvPyjcHGpVelfgMVCghXiRmLnyYBQppCFEzgxSxAqkTJfWWABXmgeaWclqt"
llIIlIllIIlIllIlllIllIllIlIIllIlllIIlIIIIlIlIllllIIIlllIIIlllIIlIlIllIIIl = 374
aAAaAaAaAAaAAAaaaAaaAaAaaaaAAaaaaAAAaaAaaaaAAaaaAAAaaAaAAAaAaaaaAAaAAaaAAaa = "kgmoEFQWIdpvUuAGipYkcxrcJncIudzIuxlBLtgKvDqRtydXEcLwbuWBqfgzZzlqBSaeWUpDiKqTMHz"
IIlIllllIIIIIllIIllIIIIlIlIlllllIIIlllIllIIIllIlIlllIlllIIIIIIlIllIllllIIIIlI = 836
AaAaaAaAaaaaaaaAAAAAaaAAAaAAAaAaAaaAaAAaAaAaaAAAaAaAaaAAAaaAaAaaaAaAaAAAAaAAAAA = "TSNZfnloCFfwSQkZKSTFRLoUtvryunfXGNmGIGDYYTXWxVBRUaurNKcesBhVDsRURsyezDkansqsmTj"
Y1654666769034757681 = "PcvQDtUuIRxbVWgKlmjIJPjYuRtprSIySFHLJQAFdMoGgbdRjWIqMyxHmdGXkOfvGFoGPgYsGbYLgjk"
lIlllIIIIIllIIIIlllIIIIIIllIIllIIIlllIllIIIIlllIlIllllIIlIlIllllllIIlIIlIIlllllllll = 302
g85 = "ipduOdYFAFRkjMGgbGuhbSfypXDwfWFmsmOtKbfwhoGEpHGnsigaLZYAtvMfvLvoosyAYqNSrTWsdoe"
lIIllllIIIIlIIIIlIIlIlIIIIlIIlIllIlIIlIllIllIIIllIlIllIlIllIlllIlIIIIIIllllllIIIlIIllII = "lRBfaOOKFZLIZmgHqNMcXpTfRmVFlaaNUAcFonBuuzoGbymMxIPmOlXiqJVxUIIKjHQhPTmKBGnsaLH"
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa = 280
IIIIlIlIlllIIIIIIIIlIIIlIIIIIIIIlllIIlIIlIIlIIIllIlllllIllIIIIIlllIlIIIIllIIIlllllIIlllIIll = "WJRvdKYoBzsAuzcMzIgwKAPMrDaRWjgbYBOsyOAEYRunrZIXsHBMeyKzLVfMBoZWvBrqYGTENzXIDUr"
AaaAAaaaaaaaAAAaAAAaAAaaAAAaaAAAaaaaaAaaaaaaaaAaaAAaAaaAaaAAAAaAAAAAaAaAAaAAaAaaaAaaaaaaaAaAA = 502
f1654666769047452295 = "BEzYYsGyqmZxbrDxMigxZelJalMfjXOHIWonZBwtnXinEwzBIPQDKnKFnIaUWMJkWMiFHkImuTIoRdy"
QztpogJlHvRwHsvLXLYQUkLrQuhiAlApjcAwnThOsoLSZoJdlIMxNTBwneufjGloZmHESORIPpTlgCc97 = "ejrBWYneEmQatwmhSNFemUNVfOJEBJrdShONlCmTXxAxlKsXowsCMRHPMMmfLBCtrFyCrmgbpTnEmJW"
p1654666769050990399 = 383
AAAaAAaAaAAAaaAaAAaAaaaaaAaaAaAaaAaaAAaaaAaaAAaAaAAaaaaaaaAaaAAaAAaaaaAaAAaaaAAaAaAAaaaAaaAAAAaAAAaaa = 222
wiSYCUloMFJQpCyzrEIbwZZMYzEJqUpfPiWsVeKYtppNDUNJJJrwkftEtwTeZHaasEMAQmnsjvdTLZu103 = 487
aAAAAAAAAaaaAAaaAAAaaAaAAaAAAaaAAAAAAAaAaAaaAaAAAaAAaaaAaaAAAaAaaAaaAaaAAaAaAAaaAaaaAAaaaaaAAaAaaaAAaAaAA = 457
aaaAAaaAaAaaaaAAAaAaaaaAaAaAaaAaAaAaAaaAAaaaAAaaAAAaaAaaAaaAaaaaaAAAAaAAAaAaaAaaaAAAaaAaAaaAaaaaaAAAAAAAAaA = 119
PjaKELhyBucGEImnijHurERnGlecRDzhbyLbLtwuDDnRzxgPYHIEghpQbagsXeyYPiehMSNiGpxvuER109 = "vnIWHBeFvSJJCnRLjKEVnGhXSBbUDwnRMYksDujFIkrrCrcUxZiwtcWueCFVqzevTXobTQYjNwrXduk"
lIllllllIlllIlIIllIlIlIllIIlIIlIlllIIIlIIIllIlIIIlIlIIlIIlIIllIIlIIllIIlIIIllIIIIllllIIIIIlllIIlllIllIlIlllIIlI = "VcfLulgYdhjLZXQmRIKbaTjfgmToMhASTfzsKRCMYZwJaxclcLsDEwAPRNLawOjmmfPdVfnkFOxTbiv"
a16546667690692494113 = "xCHTHLRapOLvstobDEbWbqibmlsheHfLSWnRZLzYyvbAbqQHbTayAkuNNQuwtwwdrstYMrXXjmjPVDz"
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE = 465
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD = 629
V16546667690718336119 = 355
lIlIlllllllllIlIIIllIlIIIllIlllIlIlIIIIIIlIlllllIIlIllIllIlIlIlllIIlIIIIIlIIlIIIllIllIlIIlIIlIlIlIllIIlIIlllIIIlIlIlIIlll = "wbuMtrerNkwTAYtXgJHcPUhtTtYqnBsEXgvcQlbdHOXvomXSnEFnswcahDplqWbpcohfRzPxfFtgyYj"
aaAAAAAaAAAAAaAaaaAAAAaAaaAAaAaAAaAAaAAAaaaAaAaaaAaAAAAaaAAaAAAaaAAAaAAaAaAaaAAaaaaAaAAaAAAAAAaaAAaAaAaaaAAAaaAaaAaaAAaAaAa = 473
S16546667690766985125 = 392
qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq = "xKeybdmunbscRRnlJbgRDJblOJcUQJmvBicevDRCccZNkcPPdMYPmEJdEWaTUUqKJiMPwSDgmqetacH"
ggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg = "OIqItOmjOjAvYOIsYERswIJZZCKGyuRcqvamMThKPlZvWDvTHYwtCJyDIKJgIrtPaXXFngAXAAHYkjx"
tmGqzoCeRGEqwawznfsCtECsEbylnYUcACPKStGEDjAHxmFlWXvWikwjrxtDbNtGUNIlzfASOTuLWVZ131 = 773
llIlIlIIlIlIIlIllIIlIlllIlIlIlIlllIIIlIIIIIlIlIlllIlIIIIIlIIIIllIlIIIlIlllIIIllIllIIllIlIIIIlllIlllllllIlIIIIIlllIllIllIIIlIIllIIIIIl = "HVHyUaFyxcTEGCAcdCsjceKHLFcvwiopcqeKnwKrfFxSprySZKkLVgnbtqBMzZoKvglVCUaqZenFUxK"
kGdSlAYyYyBHLQCYXDoXCHhfCmzOnTRzyJhFOfEvfzVROjOQEzhAlgSsVfwZSwyOJJPslRrhrxnyJIL135 = "OzWswWyBTZIdxVYezJRsAdcShfsjrYokJfklzNjuWXpAzzwhcyQmuRmUrvoBJPNRBvIOWCeaKMukUbl"
fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff = "PqFqVLfKciBojQHgYMzHxRXvzheNJVZsWterCsOaYkrjIbAJtXNadydoLzWYiVzGtdLtbZhPzRhnhkM"
IlIIIIllIlIIIIllllIIIlIllIlllIlIlllIIIIlIIlIIlIlIlIlIlIIIIlllIIIlllllllllllIlIIllllIIllIlIIIIlIllIIIlIllIIllllIllIIlIIlIlIIlIIIlIlIlllIllll = "UGKwzTWNuqnlhFlCbCvEdqjLaCTAvMDEePLdIbhnnAhjKFuSFasQEmUAPRxLDQcLGLxPQyipIqhgJER"
C141 = 345
L16546667690959105143 = 264
LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL = "YCQBZEvFvkKLGqOZYCqUyAmcCwOeROgRcBLMmsuKjRFecczeCUtmRNbFbBUWwQdmdoZQEmjZhWQtjHi"
pnHfCDiDwtgjipjKYhJzEDTUaasxtAWfIMtiHXYIVysgNyyydmXnsJqrkgqEeDnZpFOyWvRWNFhlbtn147 = 60